/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-primary-container": "#a4e88d",
        "primary-fixed-dim": "#94d77e",
        "secondary": "#855231",
        "on-surface": "#191d17",
        "surface-bright": "#f8fbf0",
        "outline-variant": "#c1c9b9",
        "on-surface-variant": "#41493d",
        "tertiary": "#603f00",
        "tertiary-fixed": "#ffddb2",
        "on-tertiary-fixed": "#291800",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#fbb890",
        "on-primary-fixed": "#022100",
        "on-tertiary": "#ffffff",
        "primary": "#125106",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eff2e7",
        "surface-container": "#ecefe5",
        "outline": "#717a6b",
        "on-secondary-container": "#794828",
        "primary-container": "#2d6a1f",
        "inverse-surface": "#2e322b",
        "secondary-container": "#febb92",
        "background": "#f8fbf0",
        "tertiary-container": "#805400",
        "surface": "#f8fbf0",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#693b1c",
        "surface-container-low": "#f2f5ea",
        "inverse-primary": "#94d77e",
        "tertiary-fixed-dim": "#ffb94c",
        "on-background": "#191d17",
        "on-tertiary-fixed-variant": "#624000",
        "surface-container-highest": "#e0e4d9",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#aff498",
        "surface-tint": "#2e6b20",
        "on-primary-fixed-variant": "#145207",
        "on-secondary-fixed": "#321300",
        "surface-dim": "#d8dbd1",
        "secondary-fixed": "#ffdbc8",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e9df",
        "on-tertiary-container": "#ffce8b",
        "surface-variant": "#e0e4d9",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "gutter": "16px",
        "container-max": "1280px",
        "unit": "4px",
        "margin": "24px",
        "touch-target-min": "44px",
      },
      fontFamily: {
        "display": ["Fraunces"],
        "label-caps": ["JetBrains Mono"],
        "h2": ["Fraunces"],
        "body-lg": ["DM Sans"],
        "h1": ["Fraunces"],
        "body-md": ["DM Sans"],
        "data-mono": ["JetBrains Mono"],
      },
      fontSize: {
        "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "h2": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "h1": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "data-mono": ["14px", {"lineHeight": "1.4", "fontWeight": "500"}],
      },
    },
  },
  plugins: [],
};
